/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RegNoRouteImport } from './routes/$regNo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRegNoRouteImport } from './routes/dashboard.$regNo'
import { Route as DashboardSplatRouteImport } from './routes/dashboard.$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegNoRoute = RegNoRouteImport.update({
  id: '/$regNo',
  path: '/$regNo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRegNoRoute = DashboardRegNoRouteImport.update({
  id: '/$regNo',
  path: '/$regNo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$regNo': typeof RegNoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/$regNo': typeof DashboardRegNoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$regNo': typeof RegNoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/$regNo': typeof DashboardRegNoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$regNo': typeof RegNoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/$regNo': typeof DashboardRegNoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$regNo'
    | '/dashboard'
    | '/dashboard/$'
    | '/dashboard/$regNo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$regNo' | '/dashboard' | '/dashboard/$' | '/dashboard/$regNo'
  id:
    | '__root__'
    | '/'
    | '/$regNo'
    | '/dashboard'
    | '/dashboard/$'
    | '/dashboard/$regNo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegNoRoute: typeof RegNoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$regNo': {
      id: '/$regNo'
      path: '/$regNo'
      fullPath: '/$regNo'
      preLoaderRoute: typeof RegNoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$regNo': {
      id: '/dashboard/$regNo'
      path: '/$regNo'
      fullPath: '/dashboard/$regNo'
      preLoaderRoute: typeof DashboardRegNoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardRegNoRoute: typeof DashboardRegNoRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardRegNoRoute: DashboardRegNoRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegNoRoute: RegNoRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
